### ISSUE TITLE
example not working with latest dependencies

### ISSUE THREAD

**Issue by sfkamath** [eivindw/hazelcast-kryo-example#1]
Hi. I remember trying this a couple of months ago and seeing it work. I noticed you've since updated the maven configuration and I can't seem to get it to work despite a few modifications. Here's what I've done so far to conform to the 2.16 kryo release

public final class KryoSerializer {

   private static final Kryo kryo = new Kryo();

   public static byte[] write(Object obj) {
       Output output = new Output(8192, 1048576);
       kryo.writeClassAndObject(output, obj);
       return output.toBytes();
   }

   public static Object read(byte[] bytes) {
       Input input = new Input();
       input.read(bytes);
       return kryo.readClassAndObject(input);
   }
}

public class KryoWrapper implements Serializable {
    private byte[] s;

```
public Object readResolve() throws ObjectStreamException {
    return KryoSerializer.read(s);
}

public KryoWrapper(Object target) {
    s = KryoSerializer.write(target);
}
```

}

The tests now seem to be broken. Registration is by default in the new kryo versions so I've commented that line in the tests. The test all break and I was wondering if you've got it to work?

Thanks
Suneet

**Comment by sfkamath** [comment]
stack trace as follows 
com.hazelcast.nio.HazelcastSerializationException: Problem when serializing type 1
    at com.hazelcast.nio.AbstractSerializer.toObject(AbstractSerializer.java:121)
    at com.hazelcast.nio.AbstractSerializer.toObject(AbstractSerializer.java:148)
    at com.hazelcast.nio.Serializer.readObject(Serializer.java:71)
    at com.hazelcast.impl.ThreadContext.toObject(ThreadContext.java:130)
    at com.hazelcast.nio.IOUtil.toObject(IOUtil.java:160)
    at com.hazelcast.impl.DefaultRecord.getValue(DefaultRecord.java:64)
    at com.hazelcast.impl.ConcurrentMapManager$MGet.get(ConcurrentMapManager.java:1046)
    at com.hazelcast.impl.MProxyImpl$MProxyReal.get(MProxyImpl.java:754)
    at com.hazelcast.impl.MProxyImpl.get(MProxyImpl.java:111)
    at eivindw.PerformanceTest.runTest(PerformanceTest.java:84)
    at eivindw.PerformanceTest.kryoWrapperValuesSerialization(PerformanceTest.java:60)
    at eivindw.PerformanceTest.runMany(PerformanceTest.java:49)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.NullPointerException
    at java.lang.System.arraycopy(Native Method)
    at com.esotericsoftware.kryo.io.Input.read(Input.java:209)
    at com.esotericsoftware.kryo.io.Input.read(Input.java:199)
    at eivindw.io.KryoSerializer.read(KryoSerializer.java:19)
    at eivindw.io.KryoWrapper.readResolve(KryoWrapper.java:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1061)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1761)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readUnshared(ObjectInputStream.java:440)
    at com.hazelcast.nio.DefaultSerializer$ObjectSerializer.readNormal(DefaultSerializer.java:410)
    at com.hazelcast.nio.DefaultSerializer$ObjectSerializer.read(DefaultSerializer.java:380)
    at com.hazelcast.nio.DefaultSerializer.read(DefaultSerializer.java:138)
    at com.hazelcast.nio.CustomSerializerAdapter.read(CustomSerializerAdapter.java:32)
    at com.hazelcast.nio.AbstractSerializer.toObject(AbstractSerializer.java:119)
    ... 36 more

**Comment by eivindw** [comment]
Thanks for noticing. Think it should work now, if you pull latest.

**Comment by sfkamath** [comment]
Great thanks
